### ISSUE TITLE
Docker support?

### ISSUE THREAD

**Issue by namlt3820** [Infisical/infisical-cli#2]
I'm interested in this project and want to integrate it with our codebase. Currently if I put `npx infisical dev node dist/index.js` in docker environment, I got an error `ENXIO: no such device or address, open '/dev/tty'`. Maybe it hasn't supported docker yet or I'm just missing some steps? Thanks for reading.

**Comment by dangtony98** [comment]
Hey thanks for asking!

We've actually received a couple requests for support for Docker recently, so we're now actively building compatibility with it and will be the next major update.

Will keep you posted!
